//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mouseclick_looper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Mouseclick_looper : global::System.Configuration.ApplicationSettingsBase {
        
        private static Mouseclick_looper defaultInstance = ((Mouseclick_looper)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Mouseclick_looper())));
        
        public static Mouseclick_looper Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Mins {
            get {
                return ((string)(this["Mins"]));
            }
            set {
                this["Mins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Secs {
            get {
                return ((string)(this["Secs"]));
            }
            set {
                this["Secs"] = value;
            }
        }
    }
}
